### ISSUE TITLE
初めの告知

### ISSUE THREAD

**Issue by machida** [asakusarb/oedo06#1]
@amatsuda 

初めの告知ページを作成しました。

### PC

![image](https://cloud.githubusercontent.com/assets/168265/22328729/20ba02e6-e401-11e6-86bc-40cbe7810f8a.png)

### スマホ

![image](https://cloud.githubusercontent.com/assets/168265/22328875/d9f932f4-e401-11e6-96c5-93dfbca53380.png)

---

ボタン部分の見た目を変更しました（https://github.com/asakusarb/oedo06/pull/2）。

![image](https://cloud.githubusercontent.com/assets/168265/22329886/b8dc6a3c-e406-11e6-95dc-66db4d161cd1.png)

---

master に静的ファイル一式をあげました。
静的ファイルを生成した元の middleman は develop ブランチにあげてあります。

まだ自動で静的ファイルを生成して master に push する仕組みは用意してません。
手元でbuildをして、そこで生成されたファイルを push しています。

確認をお願いします。

**Comment by maztomo** [comment]
:heart_eyes:

**Comment by machida** [comment]
@maztomo ありがとうございます！いただいたデザイン案のメインビジュアルの部分を全体の背景にして、全体が空っぽい感じに少しアレンジさせていただきました。

**Comment by amatsuda** [comment]
ありがとうございます！！

**Comment by amatsuda** [comment]
Deployed! https://asakusarb.github.io/oedo06/
