### ISSUE TITLE
doorkeeper をスポンサーリストとして載せる

### ISSUE THREAD

**Issue by hsbt** [asakusarb/oedo06#10]
チケット販売でスポンサードしていただいている doorkeeper をサイトのスポンサーリストに載せるというのを忘れないようにリマインダしときます!

**Comment by machida** [comment]
@hsbt リマインダありがとうございました！

![image](https://cloud.githubusercontent.com/assets/168265/23578907/8767ad96-0124-11e7-960d-df9af0843efc.png)

おかげで今回忘れず表示できました。
