### ISSUE TITLE
iPadで見たときにスポンサーロゴ画像が縦長になっている

### ISSUE THREAD

**Issue by amatsuda** [asakusarb/oedo06#33]
![oedo_ipad](https://cloud.githubusercontent.com/assets/11493/23325018/4b82ad16-fb35-11e6-88ac-99c7260a9848.jpg)

僕の試した範囲だと、PCとiPhone 6では正常、RetinaなiPadでこの状況が発生。

**Comment by machida** [comment]
@amatsuda 失礼しました！こちら修正してmasterにマージしました。

**Comment by amatsuda** [comment]
👍
