### ISSUE TITLE
Low resolution speaker photos

### ISSUE THREAD

**Issue by ujihisa** [asakusarb/oedo06#39]
なんかスピーカーの写真の解像度というか画質が本当の力を発揮してない感がします。

例: https://asakusarb.github.io/oedo06/ のmrknさん

![](https://www.gravatar.com/avatar/819b3c0a25f9708fd32261b8ae2d23f6)

github上の本気を出した画像

![](https://avatars3.githubusercontent.com/u/3959?v=3&s=460)

**Comment by machida** [comment]
@ujihisa ご指摘ありがとうございます！gravatar の urlの指定で解像度を設定できるのを知りませんでした。修正しました。
