### ISSUE TITLE
Doorkeeper立ててサイトからリンク貼る

### ISSUE THREAD

**Issue by amatsuda** [asakusarb/oedo06#4]

**Comment by machida** [comment]
@takkanm

masterを更新しました！

![image](https://cloud.githubusercontent.com/assets/168265/22692677/68c6997e-ed83-11e6-99bb-0e8544ee1b1b.png)

「参加登録」ボタンのURLにdoorkeeperのURLを設定しました。

**Comment by takkanm** [comment]
🙇

**Comment by amatsuda** [comment]
👏

**Comment by kakutani** [comment]
🥇
