### ISSUE TITLE
footerのライセンス表記にmachidaさんを載せたい

### ISSUE THREAD

**Issue by amatsuda** [asakusarb/oedo06#45]
今は"Oedo RubyKaigi 06 Team"っていうなんだかよくわからない何かにライセンスされていることになってますが、サイト自体のライセンス表記としてはデザイナー&絵描きだけで良いんじゃないかなぁ、と思いました。
それとは別にイベント自体の運営者としてAsakusa.rb(僕の個人名でもいいけど、Asakusa.rbで良いと思います)って書いておく感じでどうでしょう。

**Comment by amatsuda** [comment]
@machida ↑と思うので、ご検討お願いします！

**Comment by machida** [comment]
@amatsuda ありがとうございます！ そのようにさせていただきますー ⭐️

**Comment by machida** [comment]
このようにさせていただきました。

![image](https://cloud.githubusercontent.com/assets/168265/23831669/9d6db432-0769-11e7-80e2-d23754c27c98.png)

**Comment by kakutani** [comment]
💯

**Comment by machida** [comment]
@kakutani ご確認ありがとうございます！
