### ISSUE TITLE
タイムテーブルを作ってサイトに載せる

### ISSUE THREAD

**Issue by amatsuda** [asakusarb/oedo06#6]

**Comment by kakutani** [comment]
こちら進捗いかがでしょう?

**Comment by machida** [comment]
メモ

08:45 準備開始
09:00 開場
10:00 ごあいさつ
10:05 Ninja Talks * 3
11:05 5分休憩
11:10 招待講演
11:50 Lunch Break
13:10 Ninja Talks * 3
14:10 5分休憩
14:15 なんとか大戦(謎)
15:00 Afternoon Breakかなにか
15:15 Ninja Talks * 3
16:15 5分休憩
16:20 Keynote
17:00 全日程終了
17:15 撤収完了
17:30 懇親会開始

**Comment by machida** [comment]
完了しました。5分休憩削除も反映しました。
