### ISSUE TITLE
http://rubykaigi.org/oedo06 が https://asakusarb.github.io/oedo06 に301 Moved Permanentlyされてしまう

### ISSUE THREAD

**Issue by kakutani** [asakusarb/oedo06#9]
## 事象

http://rubykaigi.org/oedo05 はそのままproxy_passで動いているのに、06は
https://asakusarb.github.io/oedo06  に 301 Moved Permanently で転送されてしまう。

## わかったこと

rko-router: http://rubykaigi.org/oedo06 から http://asakusarb.github.io/oedo06/ にproxy_pass しようとする
gh-pages: http://asakusarb.github.io/oedo06/  は **https**://asakusarb.github.io/oedo06 に301でリダイレクトする

## 05と06の違い

github pagesの設定で 06 は「Enforce HTTPS 」にチェックがついていました。
(05はチェックがついてない)

https://help.github.com/articles/securing-your-github-pages-site-with-https/
> HTTPS enforcement is required for GitHub Pages sites created after June 15, 2016 and using a github.io domain. If you created your GitHub Pages site before June 15, 2016, you can manually enable HTTPS enforcement. HTTPS is not supported for GitHub Pages using custom domains.

## 解決策

regional.rubykaigi.org を https に対応する(ざわ…)

## 当面の回避策

宣伝用には http://regional.rubykaigi.org/oedo06 を使うことを心がける(運用回避)

**Comment by amatsuda** [comment]
おお、なるほど、SSL！しかも、最近作ったGH pagesだとSSLが必須になっちゃってるんですね。なるほど…。

**Comment by kakutani** [comment]
> 最近作ったGH pagesだとSSLが必須になっちゃってるんですね

はい。チェック外せませんでした。
時代の趨勢としてはreginal.rk.orgもrk.orgもhttpsに対応していかねばならんですね…

**Comment by kakutani** [comment]
see also: https://github.com/ruby-no-kai/official/issues/255

**Comment by hsbt** [comment]
> regional.rubykaigi.org を https に対応する(ざわ…)

root 権限もらえれば1時間もしないで対応はできなくもない...

**Comment by kakutani** [comment]
regional.rk.org の過去のコンテンツは http のものもあるんですが(oedo05とか)、
httpsのregional.rk.orgにアクセスしたときに、httpな別ドメインのhttpバックエンドに`proxy_pass`しても
nginxとしては特に問題ないのかしらん、というのが経験ないので気になってます。

**Comment by sorah** [comment]
とりいそぎ proxy_pass で https に回すのじゃダメなんですかねー

https で受けて http で他のところに流すのは nginx としては問題なく動くし、よくある構成だと思いますよ (ふつうインターネットにそのトラフィックは流れないようになると思いますが)

**Comment by kakutani** [comment]
rko-routerで動かしているbuildpackのnginxでは`https_module`が入ってなかったので、
httpsにproxy_passしたら動きませんでした…(というわけで、buildpackをいじってみます)。

**Comment by kakutani** [comment]
> httpsにproxy_passしたら動きませんでした…(というわけで、buildpackをいじってみます)

buildpackで使うnginxでhttpsを有効にしたところ、httpsへのproxy_passでエラーになる、という状況からは進展しました。

昨晩までに試したことを ruby-no-kai/rko-router#23 にdumpしました。
あちらのissueでは主に証明書どうしようかなあ…というのを相談してます。

このissueそのものについては、buildpackを新しくすればそれなりに解消されそうな目処は立ちました。
ただ、URLのtrailing slashの有無によるgh-pagesの301 redirectの仕様が悩ましいので、
nginx.confの書き方には改善の余地がありそう(ここまでが、asakusarbのあとに試したこと)

**Comment by kakutani** [comment]
ruby-no-kai/rko-router#25 でoedo06 はhttpsに`proxy_pass`するようにしました。

手元では動いているように見える(github pagesにredirectされない)のですが、いかがでしょう?

http://regional.rubykaigi.org/oedo06

**Comment by kakutani** [comment]
閉じ忘れておりました。目的は達成できたのでこちらはおしまい。
